Update bootstrap code for AOT according to:
- https://stackoverflow.com/questions/38932193/angular-2-4-5-ahead-of-time-compilation-how-to
- https://slides.com/wassimchegham/demystifying-ahead-of-time-compilation-in-angular-2-aot-jit#/26

These folks say changing to bootstrapModuleFactory is *not* required, at least when using
angular-cli (which we are not):
- https://stackoverflow.com/questions/38932193/angular-2-4-5-ahead-of-time-compilation-how-to/38933509#38933509
- https://stackoverflow.com/questions/45792911/angular-4-aot-compiler/45793323#45793323
- https://stackoverflow.com/questions/47365240/angular-5-webpack-3-aot/47469549#47469549
  (Though someone else insists: If you use platformBrowserDynamic it isn't really AoT.)

Also ref:
- https://angular.io/api/core/PlatformRef#bootstrapmodulefactory

Before changing this, I was getting this error:

ModuleNotFoundError: Module not found: Error: Can't resolve './app/app.module.ts.ngfactory' in '/webpacker_angular_csp/app/javascript/hello_angular'
resolve './app/app.module.ts.ngfactory' in '/webpacker_angular_csp/app/javascript/hello_angular'
  using description file: /webpacker_angular_csp/package.json (relative path: ./app/javascript/hello_angular)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /webpacker_angular_csp/package.json (relative path: ./app/javascript/hello_angular/app/app.module.ts.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /webpacker_angular_csp/app/javascript/hello_angular/app/app.module.ts.ngfactory doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        /webpacker_angular_csp/app/javascript/hello_angular/app/app.module.ts.ngfactory.tsx doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /webpacker_angular_csp/app/javascript/hello_angular/app/app.module.ts.ngfactory.ts doesn't exist
      …